language: java

cache:
  directories:
    - ~/.m2

matrix:
  include:
    - jdk: openjdk8
      env:
        - DESC="tests by openjdk8"
      script: mvn verify

    - jdk: oraclejdk11
      env:
        - DESC="tests by oracle11"
      script:
        - mvn clean verify

    - jdk: openjdk11
      env:
        - DESC="tests by openjdk11"
      script:
        - mvn clean verify
